### PR TITLE
[Finishes #163864697] Fix missing photo upload button during signup

### PR DESCRIPTION
**Pull request by maxwelbarno**
#### What does this PR do?
Fixes missing photo upload button
#### Description of Task to be completed?
A clickable button that links to the local file system
#### How should this be manually tested?
https://kipruto.github.io/politico-ui/ui/sign-up.html
#163864697

#### Screenshot

added upload button

### CODE REVIEW

**Comment by petermwash** [comment]
@kipruto Kindly add a screenshot of the page with the image-upload button.

**Comment by maxwelbarno** [comment]
Sorry, I have updated it with a screenshot

**Review by petermwash — APPROVED** [review]
LGTM. You can go ahead and merge it.

**Comment by maxwelbarno** [comment]
Thanks @petermwash

**Pull request merged**
